workflows:
  android-workflow:
    name: ManuX Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:

      groups:
        - keystore_credentials  # Optional - pentru signed APK
      vars:
        PACKAGE_NAME: "com.manux.manuxwealthos"
    
    scripts:
      - name: Install dependencies
        script: |
          pip install buildozer cython==0.29.36
          pip install kivy requests pillow
          pip install https://github.com/kivymd/KivyMD/archive/master.zip
          brew install autoconf automake libtool pkg-config
      
      - name: Build Android APK
        script: |
          cd android
          buildozer -v android debug
    
    artifacts:
      - android/bin/*.apk
    
    publishing:
      email:
        recipients:
          - solomio312@gmail.com
        notify:
          success: true
          failure: true
