workflows:
  android-workflow:
    name: ManuX Android Build
    max_build_duration: 60
    instance_type: linux
    
    environment:
      groups:
        - keystore_credentials  # Optional - pentru signed APK
      vars:
        PACKAGE_NAME: "com.manux.manuxwealthos"
    
    scripts:
      - name: Install dependencies
        script: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev python3-setuptools openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev
          pip install https://github.com/kivy/buildozer/archive/master.zip cython
          buildozer --version
          cython --version
          java -version
          pip install kivy requests pillow
          pip install https://github.com/kivymd/KivyMD/archive/master.zip
      
      - name: Build Android APK
        script: |
          cd android
          buildozer -v android debug
    
    artifacts:
      - android/bin/*.apk
    
    publishing:
      email:
        recipients:
          - solomio312@gmail.com
        notify:
          success: true
          failure: true
